### ISSUE TITLE
resolve formatting issue

### ISSUE THREAD

**Issue by ihor-bobyr** [shpp/programming.org.ua#25]
currently handlebars templates with partials are not supported with prettier format - https://github.com/prettier/prettier/issues/11834

1. As one of variant:
   - [ ] find available template engines according to site needs
   - [ ] change handlebars by better solution

**Comment by kateboyko** [comment]
will be fixed in scope of #73

**Comment by SitaGomes** [comment]
Thank you so much, the parser works perfectly
