### ISSUE TITLE
add anketa/last page

### ISSUE THREAD

**Issue by k-boiko** [shpp/programming.org.ua#53]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/20181140/232314183-e6e075b0-2852-46f5-96a0-0852522ed427.png">

https://programming.org.ua/ua/anketa/last

User is navigated here after submitting registration form (adults or teens).

After refreshing the page user shall be navigated to homepage.

**Comment by ihor-bobyr** [comment]
should be shown only one time, if user reloads page redirect to home page

**Comment by ihor-bobyr** [comment]
we should take email from local storage
