### ISSUE TITLE
implement ability to setup copyright in more dynamic way

### ISSUE THREAD

**Issue by ihor-bobyr** [shpp/programming.org.ua#59]
https://github.com/shpp/programming.org.ua/commit/69e9c225d2c818e5ec622e6fa4052d4bccb93078

**Comment by kateboyko** [comment]
Interesting question. I think no because it will require to make a build each year on 1st of January, and it's better to not rely on humans here :)

**Comment by ihor-bobyr** [comment]
> Interesting question. I think no because it will require to make a build each year on 1st of January, and it's better to not rely on humans here :) 

We can go with "javascript/runtime" solution, but then we will be dependent on user computer time, if it is ok, I will proceed in that way?

**Comment by kateboyko** [comment]
Discussed with Roman and decided to make both ways: firstly calculate in build time and then replace it on client side to real date if needed

**Comment by ihor-bobyr** [comment]
> Discussed with Roman and decided to make both ways: firstly calculate in build time and then replace it on client side to real date if needed

okay, will do this way
